= Resume
:layout: default
:page-permalink: /resume/

== Personal Details

[horizontal]
Name:: Aleksey Kladov
Contacts::
- icon:github[] https://github.com/matklad
- icon:link[] http://matklad.github.io
- icon:envelope[] See GitHub profile

== Education

* 2014-2016, Masters of Software Engineering (unfinished),
  *St. Petersburg State University of RAS*

* 2009-2014, Specialist of Software Engineering,
  *St. Petersburg State University*

== Professional Experience

=== Rust Programming Language
icon:calendar[title="Period"] `Sep 2015 to Now (ongoing)` +
icon:link[] https://www.rust-lang.org/governance/teams/dev-tools

I am a member of the dev-tools team of the Rust programming language. I was one
of the maintainers of https://github.com/rust-lang/cargo[Cargo] -- the package
manager for Rust. My primarily interest is IDE support.

=== Ferrous Systems
icon:calendar[title="Period"] `Sep 2018 to Now (ongoing)` +
icon:link[] https://ferrous-systems.com

At Ferrous Systems I am leading the
https://github.com/rust-analyzer/rust-analyzer[rust-analyzer/RLS-2.0] project:
an experimental next-generation compiler with a specific goal of providing
excellent IDE support for Rust.

=== Computer Science Center
icon:calendar[title="Period"] `Sep 2014 to Sep 2019` +
icon:link[] https://compscicenter.ru/teachers/934/

At CSC I taught two major courses:

Programming In Rust icon:youtube[] https://www.youtube.com/watch?v=Oy_VYovfWyo[video]::
icon:calendar[title="Period"] `Winter-Spring 2019` +
A semester long introduction course, focused on contrasting unique Rust
features with more mainstream languages like C++ or Java.

Programming In Python icon:youtube[] https://www.youtube.com/watch?v=-py9GXvJk6A[video] ::
icon:calendar[title="Period"] `Autumn-Winter 2018` +
A semester long advanced course focusing on the language inner workings and
programming idioms.

I have also worked as a teaching assistant for "Algorithms and Data structures"
and "Python" courses.

=== JetBrains
icon:calendar[title="Period"] `Sep 2015 to Jan 2018` +
icon:link[] https://intellij-rust.github.io

At JetBrains, I have lead the development of
http://github.com/intellij-rust/intellij-rust[IntelljJ-Rust] plugin for the Rust
programming language. The plugin is a Rust "compiler" written in Kotlin, with
full-blown parser, name resolution and type inference algorithms, and
integrations with build tools and debuggers. Besides solving the technical
problems, I've created an open source community around the plugin by mentoring
issues, writing developer documentation and supporting contributors.

=== Stepik.org
icon:calendar[title="Period"] `2012 to 2014` +
icon:link[] http://stepik.org/


Stepik is a e-learning platform, written in Python, focused on rich variety of
practical exercises and ease of creating content. I was on the backend team of
three from the start of the project. Among other things, I've worked on
exercises subsystem and student's code sandboxing, progress tracking and
designed and implemented JSON API interface for the single-page frontend.

=== Skills

- Rust
- Python
- Kotlin
- Compiler Frontend Development




////
# Education

I have a broad knowledge of mathematics in general (algebra, calculus, logic, optimization)
and computer science specifically (data structures, computabilty, complexity, type theory,
compilers), and I am comfortable with translating academic research ideas into robustly
working code.



# Experience


* **Stepik.org**
[Stepik]: https://stepik.org/

* **rosalind.info**

  [Rosalind] is a "project Euler" for bioinformatics, with a focus on algorithmic
  coding challenges. My responsibility at Rosalind was implementing master
  solutions, solution checkers and infrastructure around them. The primary
  language was Python, with a fair amount of C++ for the most computationally
  intensive algorithms.

[Rosalind]: http://rosalind.info

-------

I have an expert knowledge of Rust, Python and Kotlin and successfully used these
languages to deliver impactful products. I have first-hand experience with developing
production parsers, compiler front-ends and developer tools.

Most of my work is open-source, and I put significant efforts into making projects I
work on easy and enjoyable to contribute to.

You might find the following hobby-projects interesting:

- An IDE-oriented parser generator: [https://github.com/matklad/fall](https://github.com/matklad/fall)

- Tiny LISPs implemented in Rust, OCaml and themselves:
  - [https://github.com/matklad/s](https://github.com/matklad/s),
  - [https://github.com/matklad/mu](https://github.com/matklad/mu).

- A collection of ray tracers implemented in various languages:
  - [https://github.com/matklad/rustraytracer](https://github.com/matklad/rustraytracer),
  - [https://github.com/matklad/cppraytracer](https://github.com/matklad/cppraytracer),
  - [https://github.com/matklad/draytracer](https://github.com/matklad/draytracer),
  - [https://github.com/matklad/scalaraytracer](https://github.com/matklad/scalaraytracer),
  - [https://github.com/matklad/jsray](https://github.com/matklad/jsray),
  - [https://github.com/matklad/raytracer](https://github.com/matklad/raytracer).

////
